name 'kodi'
maintainer 'James Cuzella'
maintainer_email 'james.cuzella@lyraphase.com'
license 'gplv3'
description 'Installs/Configures kodi'
long_description 'Installs/Configures kodi'
version '0.1.0'
